# Generated by Django 3.0 on 2020-01-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('house_number', models.CharField(max_length=100, verbose_name='house number')),
                ('street', models.CharField(max_length=200, verbose_name='street')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('postal_code', models.CharField(max_length=100, verbose_name='postal code')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('legal_number', models.CharField(blank=True, max_length=200, verbose_name='legal number')),
                ('poc_name', models.CharField(max_length=200, verbose_name='point of contact name')),
                ('poc_phone', models.CharField(max_length=200, verbose_name='point of contact phone')),
                ('poc_email', models.CharField(max_length=200, verbose_name='point of contact email')),
                ('bank_name', models.CharField(max_length=200, verbose_name='bank name')),
                ('iban', models.CharField(max_length=200, verbose_name='IBAN number')),
                ('bic', models.CharField(blank=True, max_length=200, verbose_name='BIC number')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('adminprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='adminprofile.AdminProfile', verbose_name='AdminProfile')),
            ],
        ),
    ]
