# Generated by Django 3.0 on 2020-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200130_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bank name'),
        ),
    ]
