# Generated by Django 3.0 on 2020-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='gross_month',
            field=models.FloatField(blank=True, null=True, verbose_name='gross month'),
        ),
    ]
