# Generated by Django 3.0 on 2020-02-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20200210_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='ahv_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='AHV amount'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='alv_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='ALV amount'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='net',
            field=models.FloatField(blank=True, null=True, verbose_name='net'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pension',
            field=models.FloatField(blank=True, null=True, verbose_name='pension'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='position'),
        ),
    ]
