export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_SINGLE_COMPANY = 'GET_SINGLE_COMPANY';
export const LOGIN_USER = 'LOGIN_USER';
export const PATCH_COMPANY = 'PATCH_COMPANY';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const GET_USER_SALARY = 'GET_USER_SALARY';
export const GET_PAYDATES = 'GET_PAYDATES';
export const GET_SINGLE_PAYDATE = 'GET_SINGLE_PAYDATE';
export const SUBMIT_NEW_EMPLOYEE = 'SUBMIT_NEW_EMPLOYEE';
export const UPDATE_EMPLOYEE_PROFILE = 'UPDATE_EMPLOYEE_PROFILE';
export const GET_EMPLOYEE_RECORDS = 'GET_EMPLOYEE_RECORDS';

