# Generated by Django 3.0 on 2020-02-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('reportfiles', models.FileField(blank=True, null=True, upload_to='reportfiles/', verbose_name='reportfiles')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='company.Company', verbose_name='company')),
            ],
        ),
    ]
