# Generated by Django 3.0 on 2020-01-31 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(verbose_name='date paid')),
                ('payperiod_start', models.DateField(verbose_name='payperiod start date')),
                ('payperiod_end', models.DateField(auto_now_add=True, verbose_name='payperiod end date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='company.Company', verbose_name='company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
