# Generated by Django 3.0 on 2020-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='payperiod_end',
            field=models.DateField(verbose_name='payperiod end date'),
        ),
    ]
