# Generated by Django 3.0 on 2020-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_record_pdfstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reportstorage',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='reportstorage'),
        ),
    ]
