# Generated by Django 3.0 on 2020-02-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('record', '0004_record_reportstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='report.Report', verbose_name='report'),
        ),
    ]
